---
- hosts: localhost
  vars:
    starttime: "2023-06-18 08:00:00"
    providedtime: "2023-06-18 09:00:00"
    endtime: "2023-06-19 07:30:00"
    datetime_list:
      - "2023-06-18 08:00:00"
      - "2023-06-18 09:00:00"
      - "2023-06-18 07:30:00"

  tasks:
    - name: Compare endtime and provided time
      debug:
        msg: >
          {% if  providedtime | compare_datetimes(endtime) %}
            providedtime  is earlier than endtime
          {% else %}
            providedtime is after starttime
          {% endif %}

    - name: Compare starttime and providedtime
      debug:
        msg: >
          {% if providedtime | compare_datetimes(starttime) %}
            providedtime is earlier than starttime
          {% else %}
            provided time is after starttime
          {% endif %}


