---
- hosts: localhost
  vars:
    datetime1: "2023-06-18 08:00:00"
    providedtime: "2023-06-18 09:00:00"
    datetime2: "2023-06-19 07:30:00"
    datetime_list:
      - "2023-06-18 08:00:00"
      - "2023-06-18 09:00:00"
      - "2023-06-18 07:30:00"

  tasks:
    - name: Compare endtime and provided time
      debug:
        msg: >
          {% if  providedtime | compare_datetimes(datetime2) %}
            providedtime  is earlier than endtime
          {% else %}
            providedtime is after starttime
          {% endif %}
      register: before_end

    - name: Compare starttime and providedtime
      debug:
        msg: >
          {% if providedtime | compare_datetimes(datetime1) %}
            providedtime is earlier than starttime
          {% else %}
            provided time is after starttime
          {% endif %}
      register: after_start
    - name: Get the current time in ISO 8601 format
      set_fact:
        current_time: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"
    - name: check is provided time is in cureent time
      debug:
        msg: >
          {% if  providedtime | compare_datetimes(current_time) %}
            providedtime  is earlier than current time
          {% else %}
            providedtime is after current time
          {% endif %}
      register: time_exceed
    - name: schedule template
      shell: echo "scheduled"
      when: >
            ("provided time is after starttime" in after_start)
      
      
    
      


