---
- hosts: localhost
  vars:
    datetime1: "2023-06-18 08:00:00"
    datetime2: "2023-06-19 09:00:00"
    datetime3: "2023-06-18 10:00:00"
  tasks:
    - name: Compare date-times using custom filter
      debug:
        msg: >
          {% if datetime3 | compare_datetimes(datetime1,datetime2 ) %}
            Date-Time {{ datetime3 }} is in between {{ datetime1 }} {{ datetime2 }}
          {% else %}
            Date-Time is not in change schedule time
          {% endif %}
