---
- hosts: all
  gather_facts: false
  collections:
    - citrix.adc
  tasks:
    - name: Get lb service
      delegate_to: localhost
#      register: result
      citrix_adc_nitro_request:
        nsip: 192.168.150.131
        nitro_user: nsroot
        nitro_pass: redhat
        validate_certs: no
        operation: get
        resource: lbvserver_service_binding 
        name: "{{ item }}"
      with_items: "{{ lb_server }}"
      register: serv
   
    - debug:
        msg: "service-name {{ item.servicename }},weight {{ item.weight  }}"
      loop: "{{ serv.results | map(attribute='nitro_object') | flatten }}"
      loop_control:
        label:  "{{ item.servicename }}"
        label: "{{ item.weight }}"
