---
- hosts: all
  gather_facts: false
  collections:
    - citrix.adc
  vars:
    lb_server: server1
    service_out: {}
  tasks:
    - name: Get lb service
      delegate_to: localhost
#      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        operation: get
        resource: lbvserver_service_binding 
        name: "{{ item }}"
      with_items: "{{ lb_server }}"
      register: serv
   
    - debug:
        msg: "service-name {{ item.servicename }},weight {{ item.weight  }}"
      loop: "{{ serv.results | map(attribute='nitro_object') | flatten }}"
      loop_control:
        label:  "{{ item.servicename }}"
        label: "{{ item.weight }}"
